; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:waveshare_rp2040_zero]
platform = raspberrypi
board = generic_rp2350
framework = arduino
build_flags = -std=c++23
lib_deps = 
	nanopb/Nanopb@^0.4.91
	adafruit/Adafruit NeoPixel@^1.15.1
	adafruit/Adafruit MCP9808 Library@^2.0.2
custom_nanopb_protos = 
	+<EasyLoRa_Proto/*.proto>
